name: Update

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.14.0
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: "deploy"
      - env:
          TZ: Asia/Shanghai
        run: |
          cp deploy/db.json -T db.json
          npm install
          npm run build
          cp -r public -T deploy
          cp db.json -T deploy/db.json
          cd deploy
          rm -rf *
          git checkout HEAD -- CNAME
          git add -A
          time=`date "+%Y-%m-%d %H:%M:%S"`
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update $time"
          git push origin HEAD:gh-pages
